import 'package:flutter/material.dart';
import 'package:ismart/common/constant/assets.dart';

class CoOperative {
  CoOperative({
    required this.clientCode,
    required this.clientSecret,
    required this.coOperativeName,
    required this.bannerImage,
    required this.coOperativeLogo,
    required this.baseUrl,
    required this.splashImage,
    required this.primaryColor,
    required this.backgroundImage,
    required this.appStoreID,
    required this.packageName,
    this.shouldValidateCooperative = false,
  });

  String baseUrl;
  String clientCode;
  String clientSecret;
  String coOperativeName;
  String bannerImage;
  String coOperativeLogo;
  String splashImage;
  Color primaryColor;
  String backgroundImage;
  String appStoreID;
  String packageName;
  bool shouldValidateCooperative;

  CoOperative copyWith({required String clientCode}) {
    return CoOperative(
      clientCode: clientCode,
      clientSecret: clientSecret,
      coOperativeName: coOperativeName,
      bannerImage: bannerImage,
      coOperativeLogo: coOperativeLogo,
      baseUrl: baseUrl,
      splashImage: splashImage,
      primaryColor: primaryColor,
      backgroundImage: backgroundImage,
      appStoreID: appStoreID,
      packageName: packageName,
    );
  }
}

class CoOperativeValue {
  static final CoOperative kabilCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kabil/kabil_banner.png",
    clientCode: 'AA9ZZ33R9Z',
    clientSecret: "135639",
    // clientCode: 'VBMRDWEVFV',
    // clientSecret: "199204",
    backgroundImage: "assets/kabil/kabil_background_image.png",

    coOperativeName: 'Abhiyan',
    coOperativeLogo: "assets/kabil/kabil_logo.png",
    splashImage: "assets/kabil/kabil_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.kabil",
    appStoreID: "",
  );

  static final CoOperative abhiyanCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/abhiyan/abhiyan_banner.png",
    clientCode: 'L7CLJMN51D',
    clientSecret: "192939",
    backgroundImage: "assets/abhiyan/abhiyan_background_image.png",
    coOperativeName: 'Abhiyan',
    coOperativeLogo: "assets/abhiyan/abhiyan_logo.png",
    splashImage: "assets/abhiyan/abhiyan_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.aviyan",
    appStoreID: "",
  );
  static final CoOperative gomaGaneshCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/gomaGanesh/gomaGanesh_banner.png",
    clientCode: 'TGUUH8ZXOE',
    clientSecret: "209233",
    backgroundImage: "assets/gomaGanesh/gomaGanesh_background_image.png",
    coOperativeName: 'Goma Ganesh',
    coOperativeLogo: "assets/gomaGanesh/gomaGanesh_logo.png",
    splashImage: "assets/gomaGanesh/gomaGanesh_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.gomaGanesh",
    appStoreID: "6455685898",
  );
  static final CoOperative alankarCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/alankar/alankar_banner.png",
    clientCode: 'GY05KRRDJG',
    clientSecret: "132543",
    backgroundImage: "assets/alankar/alankar_background_image.png",
    coOperativeName: 'Abhiyan',
    coOperativeLogo: "assets/alankar/alankar_logo.png",
    splashImage: "assets/alankar/alankar_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.alankar",
    appStoreID: "6457205347",
  );
  static final CoOperative manankCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/manank/manank_banner.png",
    clientCode: 'CGJQ1YHKZ3',
    clientSecret: "149077",
    backgroundImage: "assets/manank/manank_background_image.png",
    coOperativeName: 'Abhiyan',
    coOperativeLogo: "assets/manank/manank_logo.png",
    splashImage: "assets/manank/manank_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.manank",
    appStoreID: "6457205219",
  );

  static final CoOperative arthaBagCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/arthaBag/arthaBag_banner.png",
    clientCode: 'YT2HELT9H8',
    clientSecret: "117188",
    backgroundImage: "assets/arthaBag/arthaBag_background_image.png",
    coOperativeName: 'Abhiyan',
    coOperativeLogo: "assets/arthaBag/arthaBag_logo.png",
    splashImage: "assets/arthaBag/arthaBag_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.arthabag",
    appStoreID: "",
  );

  static final CoOperative kamanaCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kamana/kamana_banner_v2.png",
    clientCode: 'LQ7QMJ5NRB',
    clientSecret: "118107",
    backgroundImage: "assets/kamana/kamana_background_image.png",
    coOperativeName: 'Kamana',
    coOperativeLogo: "assets/kamana/kamana_logo.png",
    splashImage: "assets/kamana/kamana_splash_image.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.kamana",
    appStoreID: "",
  );

  static final CoOperative uttargangaCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/uttarganga/uttarganga_banner.png",
    clientCode: '9DZS5N3TOY',
    clientSecret: "112213",
    backgroundImage: "assets/uttarganga/uttarganga_background_image.png",
    coOperativeName: 'Uttarganga',
    coOperativeLogo: "assets/uttarganga/uttarganga_logo.png",
    splashImage: "assets/uttarganga/uttarganga_splash.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.uttarganga",
    appStoreID: "",
  );

  static final CoOperative shakaryaCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sahakarya/sahakarya_banner.png",
    clientCode: 'SMTZ26RF75',
    clientSecret: "194009",
    backgroundImage: "assets/sahakarya/sahakarya_background_image.png",
    coOperativeName: 'Sahakarya',
    coOperativeLogo: "assets/sahakarya/sahakarya_logo.png",
    splashImage: "assets/sahakarya/sahakarya_splash_image.png",
    primaryColor: const Color(0xFF015017),
    packageName: "com.devanasoft.sahakarya",
    appStoreID: "6451393046",
  );

  static final CoOperative janadharaCoop = CoOperative(
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/janadhara/janadhara_banner.png",
    backgroundImage: "assets/janadhara/janadhara_background_image.png",
    clientCode: '6M0D7LSVNV',
    coOperativeName: 'Janadhara',
    coOperativeLogo: 'assets/janadhara/janadhar_logo.png',
    clientSecret: "180509",
    splashImage: "assets/janadhara/Janadhara-Splash-Resized.png",
    primaryColor: const Color(0xFF0b67bb),
    packageName: "com.devanasoft.janadhara",
    appStoreID: "6455494708",
  );

  static final CoOperative shreeaaju = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.shreeaaju",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeaaju/shreeaaju_banner.png",
    backgroundImage: "assets/shreeaaju/shreeaju_background.png",
    clientCode: 'D6CIBSGVA0',
    coOperativeName: 'Shree Aaju',
    coOperativeLogo: 'assets/shreeaaju/shreeaju_logo.png',
    clientSecret: "155993",
    splashImage: "assets/shreeaaju/shreeaaju_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeamitra = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.shreemitra",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreemitra/shreemitra_banner.png",
    backgroundImage: "assets/shreemitra/shreemitra_background.png",
    clientCode: 'JYVHE7GL7S',
    coOperativeName: 'Shree Mitra',
    coOperativeLogo: 'assets/shreemitra/shreemitra_logo.png',
    clientSecret: "128632",
    splashImage: "assets/shreemitra/shreemitra_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative kipoo = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.kipoo",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kipoo/kipoo_banner.png",
    backgroundImage: "assets/kipoo/kipoo_background.png",
    clientCode: 'JRC56V3YN4',
    coOperativeName: 'Kipoo',
    coOperativeLogo: 'assets/kipoo/kipoo_logo.png',
    clientSecret: "135559",
    splashImage: "assets/kipoo/kipoo_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative suryadev = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.suryadev",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/suryadev/suryadev_banner.png",
    backgroundImage: "assets/suryadev/suryadev_background.png",
    clientCode: 'RVERAQI2XY',
    coOperativeName: 'Suryadev',
    coOperativeLogo: 'assets/suryadev/suryadev_logo.png',
    clientSecret: "181746",
    splashImage: "assets/suryadev/suryadev_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative uddhamshil = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.suryadev",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/uddhamshil/uddhamshil_banner.png",
    backgroundImage: "assets/uddhamshil/uddhamshil_background.png",
    clientCode: 'VBJ07QPYUP',
    coOperativeName: 'Uddhamshil',
    coOperativeLogo: 'assets/uddhamshil/uddhamshil_logo.png',
    clientSecret: "133034",
    splashImage: "assets/uddhamshil/uddhamshil_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeNavaprabhat = CoOperative(
    appStoreID: "",
    packageName: "com.devanasoft.suryadev",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/navaprabhat/navaprabhat_banner.png",
    backgroundImage: "assets/navaprabhat/nawaprabhat_background_2.png",
    clientCode: '9PI6BYBK1J',
    coOperativeName: 'Shree Navaprabhat',
    coOperativeLogo: 'assets/navaprabhat/navaprabhat_logo.png',
    clientSecret: "163873",
    splashImage: "assets/navaprabhat/navaprabhat_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative vyasCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/vyas/vyas_banner.png",
    backgroundImage: "assets/vyas/vyas_background.png",
    clientCode: '5YODBM9KER',
    coOperativeName: 'Vyas',
    coOperativeLogo: 'assets/vyas/vyas_logo.png',
    clientSecret: "220475",
    splashImage: "assets/vyas/vyas_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative newDhaulagiriCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/newdhaulagiri/newdhaulagiri_banner.png",
    backgroundImage: "assets/newdhaulagiri/newdhaulagiri_background.png",
    clientCode: 'KMG1RP8OC6',
    clientSecret: "214269",
    coOperativeName: 'New Dhaulagiri',
    coOperativeLogo: 'assets/newdhaulagiri/newdhaulagiri_logo.png',
    splashImage: "assets/newdhaulagiri/newdhaulagiri_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative shreeJanamukhiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreejanamukhi/shreejanamukhi_banner.png",
    backgroundImage: "assets/shreejanamukhi/shreejanamukhi_background.png",
    clientCode: 'S9ZHZK8INB',
    clientSecret: "164605",
    coOperativeName: 'Shree Janamukhi',
    coOperativeLogo: 'assets/shreejanamukhi/shreejanamukhi_logo.png',
    splashImage: "assets/shreejanamukhi/shreejanamukhi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative ekataCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/ekata/ekata_banner.png",
    backgroundImage: "assets/ekata/ekata_background.png",
    clientCode: '0R0CQVOX1I',
    clientSecret: "217556",
    coOperativeName: 'Ekata',
    coOperativeLogo: 'assets/ekata/ekata_logo.png',
    splashImage: "assets/ekata/ekata_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative bishalSavingCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bishal/bishal_banner.png",
    backgroundImage: "assets/bishal/bishal_background.png",
    clientCode: 'VDHZQSJBBN',
    clientSecret: "212617",
    coOperativeName: 'Bishal',
    coOperativeLogo: 'assets/bishal/bishal_logo.png',
    splashImage: "assets/bishal/bishal_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sardikholaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sardikhola/sardikhola_banner.png",
    backgroundImage: "assets/sardikhola/sardikhola_background.png",
    clientCode: 'ZV9721VXYZ',
    clientSecret: "147230",
    coOperativeName: 'sardikhola',
    coOperativeLogo: 'assets/sardikhola/sardikhola_logo.png',
    splashImage: "assets/sardikhola/sardikhola_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative kripaluCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kripalu/kripalu_banner.png",
    backgroundImage: "assets/kripalu/kripalu_background.png",
    clientCode: 'HFKNI8KCA7',
    clientSecret: "198431",
    coOperativeName: 'kripalu',
    coOperativeLogo: 'assets/kripalu/kripalu_logo.png',
    splashImage: "assets/kripalu/kripalu_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
//sarbahit
  static final CoOperative sarbahitCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sarbahit/sarbahit_banner.png",
    backgroundImage: "assets/sarbahit/sarbahit_background.png",
    clientCode: '137NBD0VEA',
    clientSecret: "176079",
    coOperativeName: 'sarbahit', //Address: pokhara
    coOperativeLogo: 'assets/sarbahit/sarbahit_logo.png',
    splashImage: "assets/sarbahit/sarbahit_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sarbahitDangCoop = CoOperative(
    //Different coop

    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sarbahitDang/sarbahit_banner.png",
    backgroundImage: "assets/sarbahitDang/sarbahit_background.png",
    clientCode: '9M0432EDMA',
    clientSecret: "169999",
    coOperativeName:
        'Sarbahit Saving & Credit Co-operative Ltd', //Address: Dang
    coOperativeLogo: 'assets/sarbahitDang/sarbahit_logo.png',
    splashImage: "assets/sarbahitDang/sarbahit_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative bhanjyangCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bhanjyang/bhanjyang_banner.png",
    backgroundImage: "assets/bhanjyang/bhanjyang_background.png",
    clientCode: '9337H8GK5V',
    clientSecret: "196685",
    coOperativeName: 'bhanjyang',
    coOperativeLogo: 'assets/bhanjyang/bhanjyang_logo.png',
    splashImage: "assets/bhanjyang/bhanjyang_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative macchaPuchhreCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/macchaPuchhre/macchaPuchhre_banner.png",
    backgroundImage: "assets/macchaPuchhre/macchaPuchhre_background.png",
    clientCode: 'UO3QWA3P9M',
    clientSecret: "197951",
    coOperativeName: 'macchaPuchhre',
    coOperativeLogo: 'assets/macchaPuchhre/macchaPuchhre_logo.png',
    splashImage: "assets/macchaPuchhre/macchaPuchhre_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative nawajoshCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/nawajosh/nawajosh_banner.png",
    backgroundImage: "assets/nawajosh/nawajosh_background.png",
    clientCode: 'PWXSUF8B6F',
    clientSecret: "203542",
    coOperativeName: 'nawajosh',
    coOperativeLogo: 'assets/nawajosh/nawajosh_logo.png',
    splashImage: "assets/nawajosh/nawajosh_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative fewaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/fewa/fewa_banner.png",
    backgroundImage: "assets/fewa/fewa_background.png",
    clientCode: 'HEWD6NROMC',
    clientSecret: "156610",
    coOperativeName: 'fewa',
    coOperativeLogo: 'assets/fewa/fewa_logo.png',
    splashImage: "assets/fewa/fewa_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative matribhumiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/matribhumi/matribhumi_banner.png",
    backgroundImage: "assets/matribhumi/matribhumi_background.png",
    clientCode: 'NINX3DYNIB',
    clientSecret: "201110",
    coOperativeName: 'matribhumi',
    coOperativeLogo: 'assets/matribhumi/matribhumi_logo.png',
    splashImage: "assets/matribhumi/matribhumi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative gandakibesiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/gandakibesi/gandakibesi_banner.png",
    backgroundImage: "assets/gandakibesi/gandakibesi_background.png",
    clientCode: 'DBN0L2E9PD',
    clientSecret: "163838",
    coOperativeName: 'Gandaki Besi',
    coOperativeLogo: 'assets/gandakibesi/gandakibesi_logo.png',
    splashImage: "assets/gandakibesi/gandakibesi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative batikaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/batika/batika_banner.png",
    backgroundImage: "assets/batika/batika_background.png",
    clientCode: '276POZRR0I',
    clientSecret: "144312",
    coOperativeName: 'Batika',
    coOperativeLogo: 'assets/batika/batika_logo.png',
    splashImage: "assets/batika/batika_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative bhugolCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bhugol/bhugol_banner.png",
    backgroundImage: "assets/bhugol/bhugol_background.png",
    clientCode: 'DSZQVBJPBH',
    clientSecret: "211286",
    coOperativeName: 'Bhugol',
    coOperativeLogo: 'assets/bhugol/bhugol_logo.png',
    splashImage: "assets/bhugol/bhugol_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative nepalBachatCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/nepalbachat/nepalbachat_banner.png",
    backgroundImage: "assets/nepalbachat/nepalbachat_background.png",
    clientCode: 'VRSZGPX91G',
    clientSecret: "182223",
    coOperativeName: 'Nepal Saving and Credit Co-Operative Ltd.',
    coOperativeLogo: 'assets/nepalbachat/nepalbachat_logo.png',
    splashImage: "assets/nepalbachat/nepalbachat_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative nilgiriCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/nilgiri/nilgiri_banner.png",
    backgroundImage: "assets/nilgiri/nilgiri_background.png",
    clientCode: 'HTAENKZ3DS',
    clientSecret: "126430",
    coOperativeName: 'Nilgiri',
    coOperativeLogo: 'assets/nilgiri/nilgiri_logo.png',
    splashImage: "assets/nilgiri/nilgiri_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative davisfallCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/davisfall/davisfall_banner.png",
    backgroundImage: "assets/davisfall/davisfall_background.png",
    clientCode: 'R0CN59B1JQ',
    clientSecret: "193088",
    coOperativeName: 'davisfall',
    coOperativeLogo: 'assets/davisfall/davisfall_logo.png',
    splashImage: "assets/davisfall/davisfall_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sancharCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sanchar/sanchar_banner.png",
    backgroundImage: "assets/sanchar/sanchar_background.png",
    clientCode: 'JGDS3TK6VO',
    clientSecret: "113528",
    coOperativeName: 'sanchar',
    coOperativeLogo: 'assets/sanchar/sanchar_logo.png',
    splashImage: "assets/sanchar/sanchar_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative hamiSabaikoKrishiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/hamiSabaikokrishi/hamiSabaikokrishi_banner.png",
    backgroundImage:
        "assets/hamiSabaikokrishi/hamiSabaikokrishi_background.png",
    clientCode: 'LRIUMQ5JTT',
    clientSecret: "165705",
    coOperativeName: 'Hami Sabaiko Krishi',
    coOperativeLogo: 'assets/hamiSabaikokrishi/hamiSabaikokrishi_logo.png',
    splashImage: "assets/hamiSabaikokrishi/hamiSabaikokrishi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative rumjatarCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/rumjatar/rumjatar_banner.png",
    backgroundImage: "assets/rumjatar/rumjatar_background.png",
    clientCode: 'ZVA5CQJ8JH',
    clientSecret: "152287",
    coOperativeName: 'Rumjatar',
    coOperativeLogo: 'assets/rumjatar/rumjatar_logo.png',
    splashImage: "assets/rumjatar/rumjatar_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative supremeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/supreme/supreme_banner.png",
    backgroundImage: "assets/supreme/supreme_background.png",
    clientCode: 'CHM8BUFXX6',
    clientSecret: "156621",
    coOperativeName: 'Rumjatar',
    coOperativeLogo: 'Supreme/supreme/supreme_logo.png',
    splashImage: "assets/supreme/supreme_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeSagarmathaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sagarmatha/sagarmatha_banner.png",
    backgroundImage: "assets/sagarmatha/sagarmatha_background.png",
    clientCode: 'V9G6YBJ29X',
    clientSecret: "150239",
    coOperativeName: 'Shree Sagarmatha',
    coOperativeLogo: 'assets/sagarmatha/sagarmatha_logo.png',
    splashImage: "assets/sagarmatha/sagarmatha_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative punjaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/punja/punja_banner.png",
    backgroundImage: "assets/punja/punja_background.png",
    clientCode: 'YF0E9QARF2',
    clientSecret: "177806",
    coOperativeName: 'punja',
    coOperativeLogo: 'assets/punja/punja_logo.png',
    splashImage: "assets/punja/punja_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative immanuelCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/immanuel/immanuel_banner.png",
    backgroundImage: "assets/immanuel/immanuel_background.png",
    clientCode: 'HQ0RYHE5UW',
    clientSecret: "174569",
    coOperativeName: 'Immanuel',
    coOperativeLogo: 'assets/immanuel/immanuel_logo.png',
    splashImage: "assets/immanuel/immanuel_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative thankotMahilaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/thankotMahilaJagaran/thankot_mahila_banner.png",
    backgroundImage:
        "assets/thankotMahilaJagaran/thankot_mahila_background.png",
    clientCode: '0PY5GD8HOF',
    clientSecret: "176436",
    coOperativeName: 'Thankot MahilaJagaran',
    coOperativeLogo: 'assets/thankotMahilaJagaran/thankot_mahila_logo.png',
    splashImage: "assets/thankotMahilaJagaran/thankot_mahila_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative bishnudolCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bishnudol/bishnudol_banner.png",
    backgroundImage: "assets/bishnudol/bishnudol_background.png",
    clientCode: 'DGT7IPWJ57',
    clientSecret: "146811",
    coOperativeName: 'Bishnudol',
    coOperativeLogo: 'assets/bishnudol/bishnudol_logo.png',
    splashImage: "assets/bishnudol/bishnudol_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative annapurnaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/annapurna/annapurna_banner.png",
    backgroundImage: "assets/annapurna/annapurna_background.png",
    clientCode: '9LMVZK6Y3Z',
    clientSecret: "138827",
    coOperativeName: 'annapurna Health ',
    coOperativeLogo: 'assets/annapurna/annapurna_logo.png',
    splashImage: "assets/annapurna/annapurna_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative kanchanjunghaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kanchanjungha/kanchanjungha_banner.png",
    backgroundImage: "assets/kanchanjungha/kanchanjungha_background.png",
    clientCode: 'WBSSRVSEB9',
    clientSecret: "187636",
    coOperativeName: 'Kanchanjangha Multipurpose Co-operative Ltd	',
    coOperativeLogo: 'assets/kanchanjungha/kanchanjungha_logo.png',
    splashImage: "assets/kanchanjungha/kanchanjungha_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative janasewaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/janasewa/janasewa_banner.png",
    backgroundImage: "assets/janasewa/janasewa_background.png",
    clientCode: 'W5QT17Z880',
    clientSecret: "171279",
    coOperativeName: 'Janasewa',
    coOperativeLogo: 'assets/janasewa/janasewa_logo.png',
    splashImage: "assets/janasewa/janasewa_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative goldenCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/golden/golden_banner.png",
    backgroundImage: "assets/golden/golden_background.png",
    clientCode: '7OMBGHP0O6',
    clientSecret: "157652",
    coOperativeName: 'Golden',
    coOperativeLogo: 'assets/golden/golden_logo.png',
    splashImage: "assets/golden/golden_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  //For test
  static final CoOperative iconSoftCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/iconsoftCoop/iconsoft_banner.png",
    backgroundImage: "assets/iconsoftCoop/iconsoft_background.png",
    clientCode: 'OI6XM76XZT',
    clientSecret: "190021",
    coOperativeName: 'IconSoft',
    coOperativeLogo: 'assets/iconsoftCoop/iconsoft_logo.png',
    splashImage: "assets/iconsoftCoop/iconsoft_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative royalGorkhaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/royalGorkha/royalGorkha_banner.png",
    backgroundImage: "assets/royalGorkha/royalGorkha_background.png",
    clientCode: 'VY5ZJ7PFHJ',
    clientSecret: "217188",
    coOperativeName: 'Royal Gorkha Multipurpose',
    coOperativeLogo: 'assets/royalGorkha/royalGorkha_logo.png',
    splashImage: "assets/royalGorkha/royalGorkha_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative buddhaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/buddhaCoop/buddha_banner.png",
    backgroundImage: "assets/buddhaCoop/buddha_background.png",
    clientCode: 'I42M8ZXXB6',
    clientSecret: "207412",
    coOperativeName: 'Buddha Saving & Credit',
    coOperativeLogo: 'assets/buddhaCoop/buddha_logo.png',
    splashImage: "assets/buddhaCoop/buddha_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative nayanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/nayan/nayan_banner.png",
    backgroundImage: "assets/nayan/nayan_background.png",
    clientCode: 'DQKWL4X17Y',
    clientSecret: "118273",
    coOperativeName: 'Nayan Saving & Credit',
    coOperativeLogo: 'assets/nayan/nayan_logo.png',
    splashImage: "assets/nayan/nayan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative rithepaniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/rithepani/rithepani_banner.png",
    backgroundImage: "assets/rithepani/rithepani_background.png",
    clientCode: 'SGGSLNACQN',
    clientSecret: "207387",
    coOperativeName: 'Rithepani Saving & Credit',
    coOperativeLogo: 'assets/rithepani/rithepani_logo.png',
    splashImage: "assets/rithepani/rithepani_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative shreeSubhakamanaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeSubhakamana/shree_subhakamana_banner.png",
    backgroundImage: "assets/shreeSubhakamana/shree_subhakamana_background.png",
    clientCode: 'LC8A4TC6AX',
    clientSecret: "116572",
    coOperativeName: 'Shree ShubhaKamana MultiPurpose',
    coOperativeLogo: 'assets/shreeSubhakamana/shree_subhakamana_logo.png',
    splashImage: "assets/shreeSubhakamana/shree_subhakamana_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative bishalMultiPurposeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bishalMulti/bishalMulti_banner.png",
    backgroundImage: "assets/bishalMulti/bishalMulti_background.png",
    clientCode: 'BHHZB5DT3H',
    clientSecret: "172650",
    coOperativeName: 'Bishal Multipurpose Co-Operative Ltd.',
    coOperativeLogo: 'assets/bishalMulti/bishalMulti_logo.png',
    splashImage: "assets/bishalMulti/bishalMulti_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative sanaKishanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sanakishan/sanakishan_banner.png",
    backgroundImage: "assets/sanakishan/sanakishan_background.png",
    clientCode: 'RPJTJAKDBR',
    clientSecret: "203763",
    coOperativeName: 'SFACL Niglihawa',
    coOperativeLogo: 'assets/sanakishan/sanakishan_logo.png',
    splashImage: "assets/sanakishan/sanakishan_splash.png",
    shouldValidateCooperative: true,
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeMyagdeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeMyagde/shreeMyagde_banner.png",
    backgroundImage: "assets/shreeMyagde/shreeMyagde_background.png",
    clientCode: 'AG7KQ7NBUC',
    clientSecret: "160745",
    coOperativeName: 'Shree Myagde Dugdha Utpadak Cooperative Ltd',
    coOperativeLogo: 'assets/shreeMyagde/shreeMyagde_logo.png',
    splashImage: "assets/shreeMyagde/shreeMyagde_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative vaidhikCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/vaidhik/vaidhik_banner.png",
    backgroundImage: "assets/vaidhik/vaidhik_background.png",
    clientCode: '8QASJZYBA6',
    clientSecret: "131917",
    coOperativeName: 'Vaidhik Multipurpose Cooperative Ltd',
    coOperativeLogo: 'assets/vaidhik/vaidhik_logo.png',
    splashImage: "assets/vaidhik/vaidhik_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeKalikaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeKalika/shreeKalika_banner.png",
    backgroundImage: "assets/shreeKalika/shreeKalika_background.png",
    clientCode: 'J0JDLK7OFX',
    clientSecret: "132342",
    coOperativeName: 'ShreeKalika Saving and Credit Cooperative Ltd	',
    coOperativeLogo: 'assets/shreeKalika/shreeKalika_logo.png',
    splashImage: "assets/shreeKalika/shreeKalika_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeHemjaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeHemja/shreeHemja_banner.png",
    backgroundImage: "assets/shreeHemja/shreeHemja_background.png",
    clientCode: 'YZGRJX3M6Z',
    clientSecret: "117248",
    coOperativeName: 'Shree Hemja Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/shreeHemja/shreeHemja_logo.png',
    splashImage: "assets/shreeHemja/shreeHemja_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shubhodayaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/subhodaya/subhodaya_banner.png",
    backgroundImage: "assets/subhodaya/subhodaya_background.png",
    clientCode: 'SJ24IDUMP1',
    clientSecret: "146404",
    coOperativeName: 'Shubhodaya Multipurpose Co-operative Ltd',
    coOperativeLogo: 'assets/subhodaya/subhodaya_logo.png',
    splashImage: "assets/subhodaya/subhodaya_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative garimaAgriCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/garimaAgri/garimaAgri_banner.png",
    backgroundImage: "assets/garimaAgri/garimaAgri_background.png",
    clientCode: 'OPSM0RJ5LH',
    clientSecret: "156691",
    coOperativeName: 'Garima Agriculture Co-operative Ltd.',
    coOperativeLogo: 'assets/garimaAgri/garimaAgri_logo.png',
    splashImage: "assets/garimaAgri/garimaAgri_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative aasthaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/aastha/aastha_banner.png",
    backgroundImage: "assets/aastha/aastha_background.png",
    clientCode: 'H86KG3CCDO',
    clientSecret: "184352",
    splashImage: "assets/aastha/aastha_splash.png",
    coOperativeName: 'Aastha Saving and Credit Co-operative Society Ltd',
    coOperativeLogo: 'assets/aastha/aastha_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative chirayuCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/chirayu/chirayu_banner.png",
    backgroundImage: "assets/chirayu/chirayu_background.png",
    clientCode: 'XTRYL40R9O',
    clientSecret: "219645",
    splashImage: "assets/chirayu/chirayu_splash.png",
    coOperativeName: 'Chirayu Multipurpose Co-operative Ltd',
    coOperativeLogo: 'assets/chirayu/chirayu_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative paschimanchalCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/paschimanchal/paschimanchal_banner.png",
    backgroundImage: "assets/paschimanchal/paschimanchal_background.png",
    clientCode: '7FF8IH0E1S',
    clientSecret: "157999",
    splashImage: "assets/paschimanchal/paschimanchal_splash.png",
    coOperativeName: 'Paschimanchal Health Cooperative	',
    coOperativeLogo: 'assets/paschimanchal/paschimanchal_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative digitalCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/digitalCoop/digitalCoop_banner.png",
    backgroundImage: "assets/digitalCoop/digitalCoop_background.png",
    clientCode: 'HCXZNBLLII',
    clientSecret: "164512",
    splashImage: "assets/digitalCoop/digitalCoop_splash.png",
    coOperativeName: 'Digital Multipurpose Co-operative Ltd',
    coOperativeLogo: 'assets/digitalCoop/digitalCoop_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative upakarCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/upakar/upakar_banner.png",
    backgroundImage: "assets/upakar/upakar_background.png",
    clientCode: '84VHCKC8U3',
    clientSecret: "159493",
    splashImage: "assets/upakar/upakar_splash.png",
    coOperativeName: 'Upakar Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/upakar/upakar_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sunshineCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sunshine/sunshine_banner.png",
    backgroundImage: "assets/sunshine/sunshine_background.png",
    clientCode: '0FKODTJ7G9',
    clientSecret: "194796",
    coOperativeName: 'Sunshine Saving and Credit Co-operative Society Ltd',
    coOperativeLogo: 'assets/sunshine/sunshine_logo.png',
    splashImage: "assets/sunshine/sunshine_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative uttarbahiniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/uttarbahini/uttarbahini_banner.png",
    backgroundImage: "assets/uttarbahini/uttarbahini_background.png",
    clientCode: 'YQK7VL2FJ7',
    clientSecret: "142120",
    coOperativeName: 'Uttarbahini Multipurpose Co-operative LTD.',
    coOperativeLogo: 'assets/uttarbahini/uttarbahini_logo.png',
    splashImage: "assets/uttarbahini/uttarbahini_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative noorCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/noor/noor_banner.png",
    backgroundImage: "assets/noor/noor_background.png",
    clientCode: '8S1I28RT16',
    clientSecret: "208165",
    coOperativeName: 'NOOR Multipurpose Co-operative LTD.',
    coOperativeLogo: 'assets/noor/noor_logo.png',
    splashImage: "assets/noor/noor_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sudarshanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sudarshan/sudarshan_banner.png",
    backgroundImage: "assets/sudarshan/sudarshan_background.png",
    clientCode: 'AWXKVB17TV',
    clientSecret: "189674",
    coOperativeName: 'Sudarshan Saving and Credit Co-operative Limited',
    coOperativeLogo: 'assets/sudarshan/sudarshan_logo.png',
    splashImage: "assets/sudarshan/sudarshan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative shubhaSandeshCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shubhaSandesh/shubha_sandesh_banner.png",
    backgroundImage: "assets/shubhaSandesh/shubha_sandesh_background.png",
    clientCode: 'JCJY7XP42T',
    clientSecret: "149163",
    coOperativeName: 'Shubha Sandesh Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/shubhaSandesh/shubha_sandesh_logo.png',
    splashImage: "assets/shubhaSandesh/shubha_sandesh_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative metrangCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/metrang/metrang_banner.png",
    backgroundImage: "assets/metrang/metrang_background.png",
    clientCode: 'I6ZCYOGUFO',
    clientSecret: "173517",
    coOperativeName: 'Metrang Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/metrang/metrang_logo.png',
    splashImage: "assets/metrang/metrang_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative indreniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/indreni/indreni_banner.png",
    backgroundImage: "assets/indreni/indreni_background.png",
    clientCode: 'PLKPBMSN7M',
    clientSecret: "194012",
    coOperativeName: 'Indreni Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/indreni/indreni_logo.png',
    splashImage: "assets/indreni/indreni_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sanakishanHathasuwaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sanakishanHathasuwa/sanakisan_hathasuwa_banner.png",
    backgroundImage:
        "assets/sanakishanHathasuwa/sanakisan_hathasuwa_background.png",
    clientCode: 'S2KWS4JMTT',
    clientSecret: "141752",
    coOperativeName: 'Sana Kisan Agriculture Cooperative Ltd Hathausa',
    coOperativeLogo: 'assets/sanakishanHathasuwa/sanakisan_hathasuwa_logo.png',
    splashImage: "assets/sanakishanHathasuwa/sanakisan_hathasuwa_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative avatarCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/avatar/avatar_banner.png",
    backgroundImage: "assets/avatar/avatar_background.png",
    clientCode: '5X3VCMWQN0',
    clientSecret: "111255",
    coOperativeName: 'avatar Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/avatar/avatar_logo.png',
    splashImage: "assets/avatar/avatar_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative chaughadaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/chaughada/chaughada_banner.png",
    backgroundImage: "assets/chaughada/chaughada_background.png",
    clientCode: '315US6F1SX',
    clientSecret: "114273",
    coOperativeName: 'Chaughada Saving & Credit Co-Operative Society Ltd.',
    coOperativeLogo: 'assets/chaughada/chaughada_logo.png',
    splashImage: "assets/chaughada/chaughada_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative hetaudaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/hetauda/hetauda_banner.png",
    backgroundImage: "assets/hetauda/hetauda_background.png",
    clientCode: 'XRVHIOR64A',
    clientSecret: "216602",
    coOperativeName: 'Hetauda Saving & Credit Co-Operative Ltd',
    coOperativeLogo: 'assets/hetauda/hetauda_logo.png',
    splashImage: "assets/hetauda/hetauda_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative youthVoiceCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/youthvoice/youthvoice_banner.png",
    backgroundImage: "assets/youthvoice/youthvoice_background.png",
    clientCode: 'WCZ8TW1S1P',
    clientSecret: "137947",
    coOperativeName: 'Youth Voice Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/youthvoice/youthvoice_logo.png',
    splashImage: "assets/youthvoice/youthvoice_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative pragatishilCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/pragatishil/pragatishil_banner.png",
    backgroundImage: "assets/pragatishil/pragatishil_background.png",
    clientCode: 'KFK94JBG3T',
    clientSecret: "152137",
    coOperativeName: 'Pragatishil Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/pragatishil/pragatishil_logo.png',
    splashImage: "assets/pragatishil/pragatishil_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shitalCoop = CoOperative(
    //shree removed form name
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shital/shital_banner.png",
    backgroundImage: "assets/shital/shital_background.png",
    clientCode: 'JVE6CTMBM0',
    clientSecret: "166409",
    splashImage: "assets/shital/shital_splash.png",
    coOperativeName: 'Shital Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/shital/shital_logo.png',
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative darshanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/darshan/darshan_banner.png",
    backgroundImage: "assets/darshan/darshan_background.png",
    clientCode: '73NJJ0P2V8',
    clientSecret: "170801",
    coOperativeName: 'Darshan Saving & Credit Cooperative Ltd.',
    coOperativeLogo: 'assets/darshan/darshan_logo.png',
    splashImage: "assets/darshan/darshan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative smartUdhamshilCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/smartUddhamshil/smartUddhamshil_banner.png",
    backgroundImage: "assets/smartUddhamshil/smartUddhamshil_background.png",
    clientCode: 'N5T3CEJ181',
    clientSecret: "138633",
    coOperativeName: 'Smart Udhamshil Co-Operative Ltd',
    coOperativeLogo: 'assets/smartUddhamshil/smartUddhamshil_logo.png',
    splashImage: "assets/smartUddhamshil/smartUddhamshil_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative udhamshilKrishiYantrikCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/uddhamshilKrishi/uddhamshil_krishi_banner.png",
    backgroundImage: "assets/uddhamshilKrishi/uddhamshil_krishi_background.png",
    clientCode: 'ZPOP3RQEFJ',
    clientSecret: "185109",
    coOperativeName: 'Udhamshil Krishi Yantrikaran Co-operative Ltd.',
    coOperativeLogo: 'assets/uddhamshilKrishi/uddhamshil_krishi_logo.png',
    splashImage: "assets/uddhamshilKrishi/uddhamshil_krishi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeDigopanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeDigopan/shreeDigopan_banner.png",
    backgroundImage: "assets/shreeDigopan/shreeDigopan_background.png",
    clientCode: '306KNIDTNO',
    clientSecret: "146815",
    coOperativeName: 'Shree Digopan Samajik Udhami Mahila Sahakari Sanstha Ltd',
    coOperativeLogo: 'assets/shreeDigopan/shreeDigopan_logo.png',
    splashImage: "assets/shreeDigopan/shreeDigopan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative queenCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/queenCoop/queen_banner.png",
    backgroundImage: "assets/queenCoop/queen_background.png",
    clientCode: 'NES36H9DCV',
    clientSecret: "196955",
    coOperativeName: 'Queen Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/queenCoop/queen_logo.png',
    splashImage: "assets/queenCoop/queen_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative nayaKiranCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/nayakiran/nayakiran_banner.png",
    backgroundImage: "assets/nayakiran/nayakiran_background.png",
    clientCode: 'ZJE3W8JRYD',
    clientSecret: "116975",
    coOperativeName: 'Naya Kiran Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/nayakiran/nayakiran_logo.png',
    splashImage: "assets/nayakiran/nayakiran_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative kendrabinduCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/kendrabindu/kendrabindu_banner.png",
    backgroundImage: "assets/kendrabindu/kendrabindu_background.png",
    clientCode: 'S2S87QYX5O',
    clientSecret: "179940",
    coOperativeName: 'Kendrabindu multipurpose sahakari sanstha Ltd.',
    coOperativeLogo: 'assets/kendrabindu/kendrabindu_logo.png',
    splashImage: "assets/kendrabindu/kendrabindu_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative eastwestCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/eastwest/eastwest_banner.png",
    backgroundImage: "assets/eastwest/eastwest_background.png",
    clientCode: 'OKYT63VF2S',
    clientSecret: "210721",
    coOperativeName: 'East West Saving and Credit Cooperative Ltd.',
    coOperativeLogo: 'assets/eastwest/eastwest_logo.png',
    splashImage: "assets/eastwest/eastwest_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative babiraCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/babira/babira_banner.png",
    backgroundImage: "assets/babira/babira_background.png",
    clientCode: '2VNQVLC1Z9',
    clientSecret: "131433",
    coOperativeName: 'Babira Multipurpose Cooperative Limited.',
    coOperativeLogo: 'assets/babira/babira_logo.png',
    splashImage: "assets/babira/babira_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative devshreeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/devshree/devshree_banner.png",
    backgroundImage: "assets/devshree/devshree_background.png",
    clientCode: '9B3YEMMDY2',
    clientSecret: "197212",
    coOperativeName: 'Devashree Saving and Credit Co-operative Ltd',
    coOperativeLogo: 'assets/devshree/devshree_logo.png',
    splashImage: "assets/devshree/devshree_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative ektaMultipurposeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/ektaMultipurpose/ektaMulti_banner.png",
    backgroundImage: "assets/ektaMultipurpose/ektaMulti_background.png",
    clientCode: 'Z99TZE0GKZ',
    clientSecret: "113270",
    coOperativeName: 'Ekta Multipurpose Cooperative Limited.',
    coOperativeLogo: 'assets/ektaMultipurpose/ektaMulti_logo.png',
    splashImage: "assets/ektaMultipurpose/ektaMulti_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shwetbhairabCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shwetbhairab/shwetbhairab_banner.png",
    backgroundImage: "assets/shwetbhairab/shwetbhairab_background.png",
    clientCode: '98ZAC5SMQB',
    clientSecret: "191770",
    coOperativeName: 'ShwetBhairab Saving and Credit Co-operative Ltd',
    coOperativeLogo: 'assets/shwetbhairab/shwetbhairab_logo.png',
    splashImage: "assets/shwetbhairab/shwetbhairab_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative karmathCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/karmath/karmath_banner.png",
    backgroundImage: "assets/karmath/karmath_background.png",
    clientCode: 'XCNY87XJGV',
    clientSecret: "220744",
    coOperativeName: 'Karmath Samajik Uddhami Mahila Sahakari Sastha Limited',
    coOperativeLogo: 'assets/karmath/karmath_logo.png',
    splashImage: "assets/karmath/karmath_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeEkataCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeEkata/shreeEkata_banner.png",
    backgroundImage: "assets/shreeEkata/shreeEkata_background.png",
    clientCode: 'NHQZWVPYQJ',
    clientSecret: "151694",
    coOperativeName: 'ShreeEkata Saving and Credit Co-Operative Ltd',
    coOperativeLogo: 'assets/shreeEkata/shreeEkata_logo.png',
    splashImage: "assets/shreeEkata/shreeEkata_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeJanaEkikritCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeJanaEkikrit/shreeJanaEkikrit_banner.png",
    backgroundImage: "assets/shreeJanaEkikrit/shreeJanaEkikrit_background.png",
    clientCode: '6139Y4LZ2F',
    clientSecret: "170370",
    coOperativeName: 'Shree Jana Ekikrit Multipurpose Co-operative Society Ltd',
    coOperativeLogo: 'assets/shreeJanaEkikrit/shreeJanaEkikrit_logo.png',
    splashImage: "assets/shreeJanaEkikrit/shreeJanaEkikrit_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeSiddhiGaneshCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeSiddhiGanesh/shreeSiddhiGanesh_banner.png",
    backgroundImage:
        "assets/shreeSiddhiGanesh/shreeSiddhiGanesh_background.png",
    clientCode: 'KTAVSCY9WQ',
    clientSecret: "212150",
    coOperativeName: 'Shree Siddi Ganesh Saving & Credit Co-operative Ltd',
    coOperativeLogo: 'assets/shreeSiddhiGanesh/shreeSiddhiGanesh_logo.png',
    splashImage: "assets/shreeSiddhiGanesh/shreeSiddhiGanesh_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative mithilaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/mithila/mithila_banner.png",
    backgroundImage: "assets/mithila/mithila_background.png",
    clientCode: 'A836WR7RBM',
    clientSecret: "181433",
    coOperativeName: 'Mithila Saving and Credit Co-operative Pvt. Ltd',
    coOperativeLogo: 'assets/mithila/mithila_logo.png',
    splashImage: "assets/mithila/mithila_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeMahilaTarkariCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeMahilaTarkari/shreeMahilaTarkari_banner.png",
    backgroundImage:
        "assets/shreeMahilaTarkari/shreeMahilaTarkari_background.png",
    clientCode: 'BZB7NFYQS8',
    clientSecret: "211773",
    coOperativeName:
        'Shree Mahila Tarkari Byabasai Saving and Credit Co-operative Limited',
    coOperativeLogo: 'assets/shreeMahilaTarkari/shreeMahilaTarkari_logo.png',
    splashImage: "assets/shreeMahilaTarkari/shreeMahilaTarkari_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative aaratiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/aarati/aarati_banner.png",
    backgroundImage: "assets/aarati/aarati_background.png",
    clientCode: 'PHZDAEF1CW',
    clientSecret: "156872",
    coOperativeName: 'Aarati Saving and Credit Co-operative Ltd',
    coOperativeLogo: 'assets/aarati/aarati_logo.png',
    splashImage: "assets/aarati/aarati_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative janataCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/janata/janata_banner.png",
    backgroundImage: "assets/janata/janata_background.png",
    clientCode: 'WZO4YQO6F6',
    clientSecret: "165161",
    coOperativeName: 'Janata Multipurpose Co-operative Limited',
    coOperativeLogo: 'assets/janata/janata_logo.png',
    splashImage: "assets/janata/janata_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative agrasarCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/agrasar/agrasar_banner.png",
    backgroundImage: "assets/agrasar/agrasar_background.png",
    clientCode: '60851K9IMW',
    clientSecret: "156581",
    coOperativeName: 'agrasar Saving and Credit Co-operative Pvt. Ltd',
    coOperativeLogo: 'assets/agrasar/agrasar_logo.png',
    splashImage: "assets/agrasar/agrasar_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative khotangJaleshworiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/khotangJaleshwori/khotangJaleshwori_banner.png",
    backgroundImage:
        "assets/khotangJaleshwori/khotangJaleshwori_background.png",
    clientCode: 'SJ4IRJJQEO',
    clientSecret: "135763",
    coOperativeName:
        'Khotang Jaleshwori Saving and Credit Co-operative Pvt. Ltd',
    coOperativeLogo: 'assets/khotangJaleshwori/khotangJaleshwori_logo.png',
    splashImage: "assets/khotangJaleshwori/khotangJaleshwori_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeMitereeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeMiteree/shreeMiteree_banner.png",
    backgroundImage: "assets/shreeMiteree/shreeMiteree_background.png",
    clientCode: 'R5JUKWMHK7',
    clientSecret: "111804",
    coOperativeName: 'Shree Miteree Saving and Credit Cooperative ltd',
    coOperativeLogo: 'assets/shreeMiteree/shreeMiteree_logo.png',
    splashImage: "assets/shreeMiteree/shreeMiteree_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative puspanjaliCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/puspanjali/puspanjali_banner.png",
    backgroundImage: "assets/puspanjali/puspanjali_background.png",
    clientCode: '0R05P85NRG',
    clientSecret: "182841",
    coOperativeName: 'Puspanjali Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/puspanjali/puspanjali_logo.png',
    splashImage: "assets/puspanjali/puspanjali_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative aakashbaniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/aakashbani/aakashbani_banner.png",
    backgroundImage: "assets/aakashbani/aakashbani_background.png",
    clientCode: 'IPUSNJ3AJF',
    clientSecret: "194455",
    coOperativeName: 'Aakashbani Saving and Credit Cooperative Pvt Ltd',
    coOperativeLogo: 'assets/aakashbani/aakashbani_logo.png',
    splashImage: "assets/aakashbani/aakashbani_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeAmrapaliCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/amrapali/amrapali_banner.png",
    backgroundImage: "assets/amrapali/amrapali_background.png",
    clientCode: 'BGJW1YZF5M',
    clientSecret: "172325",
    coOperativeName: 'Shree Amrapali Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/amrapali/amrapali_logo.png',
    splashImage: "assets/amrapali/amrapali_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative autobikashCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/autobikash/autobikash_banner.png",
    backgroundImage: "assets/autobikash/autobikash_background.png",
    clientCode: 'XKQPM6WHFO',
    clientSecret: "126375",
    coOperativeName: 'Auto Bikash Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/autobikash/autobikash_logo.png',
    splashImage: "assets/autobikash/autobikash_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative starlightCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/starlight/starlight_banner.png",
    backgroundImage: "assets/starlight/starlight_background.png",
    clientCode: 'ND53ZGJ4IE',
    clientSecret: "197881",
    coOperativeName: 'Starlight Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/starlight/starlight_logo.png',
    splashImage: "assets/starlight/starlight_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative shreeMarsyangdiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeMarsyangdi/shreeMarsyangdi_banner.png",
    backgroundImage: "assets/shreeMarsyangdi/shreeMarsyangdi_background.png",
    clientCode: 'A99TH6FB12',
    clientSecret: "191225",
    coOperativeName: 'Shree Marsyangdi Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/shreeMarsyangdi/shreeMarsyangdi_logo.png',
    splashImage: "assets/shreeMarsyangdi/shreeMarsyangdi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative tanahunKalikaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/tanahunKalika/tanahunKalika_banner.png",
    backgroundImage: "assets/tanahunKalika/tanahunKalika_background.png",
    clientCode: 'U82ELN31YI',
    clientSecret: "218380",
    coOperativeName: 'Tanahun Kalika Saving and Credit Cooperative Ltd	',
    coOperativeLogo: 'assets/tanahunKalika/tanahunKalika_logo.png',
    splashImage: "assets/tanahunKalika/tanahunKalika_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative khullabajarCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/khullabajar/khullabajar_banner.png",
    backgroundImage: "assets/khullabajar/khullabajar_background.png",
    clientCode: 'FXUBBEG3VP',
    clientSecret: "124580",
    coOperativeName: 'Khulla Bajar Saving and Credit Co-operative Limited	',
    coOperativeLogo: 'assets/khullabajar/khullabajar_logo.png',
    splashImage: "assets/khullabajar/khullabajar_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative abhibadanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/abhibadan/abhibadan_banner.png",
    backgroundImage: "assets/abhibadan/abhibadan_background.png",
    clientCode: 'WQPWTJYR85',
    clientSecret: "179061",
    coOperativeName: 'Abhibadan Multipurpose Co-operative Society Limited',
    coOperativeLogo: 'assets/abhibadan/abhibadan_logo.png',
    splashImage: "assets/abhibadan/abhibadan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative lifeVisionCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/lifeVision/lifeVision_banner.png",
    backgroundImage: "assets/lifeVision/lifeVision_background.png",
    clientCode: 'VN9ZMLS8PT',
    clientSecret: "169878",
    coOperativeName: 'Life Vision Saving & Credit Co-operative Limited',
    coOperativeLogo: 'assets/lifeVision/lifeVision_logo.png',
    splashImage: "assets/lifeVision/lifeVision_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative chandaniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/chandani/chandani_banner.png",
    backgroundImage: "assets/chandani/chandani_background.png",
    clientCode: '7IMKC3F79F',
    clientSecret: "199867",
    coOperativeName: 'Chandani Saving and Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/chandani/chandani_logo.png',
    splashImage: "assets/chandani/chandani_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative sparklingCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/sparkling/sparkling_banner.png",
    backgroundImage: "assets/sparkling/sparkling_background.png",
    clientCode: '4AJJY4XH26',
    clientSecret: "217254",
    coOperativeName: 'Sparkling Agricultural Co-operative Limited	',
    coOperativeLogo: 'assets/sparkling/sparkling_logo.png',
    splashImage: "assets/sparkling/sparkling_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative pacificCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/pacific/pacific_banner.png",
    backgroundImage: "assets/pacific/pacific_background.png",
    clientCode: 'M66VVYESH8',
    clientSecret: "126072",
    coOperativeName: 'Pacific Saving and Credit Co-operative Limited',
    coOperativeLogo: 'assets/pacific/pacific_logo.png',
    splashImage: "assets/pacific/pacific_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative samutthanCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/samutthan/samutthan_banner.png",
    backgroundImage: "assets/samutthan/samutthan_background.png",
    clientCode: 'RF0O6228ND',
    clientSecret: "143283",
    coOperativeName: 'Samutthan Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/samutthan/samutthan_logo.png',
    splashImage: "assets/samutthan/samutthan_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative hamroDahachokCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/hamroDahachok/hamroDahachok_banner.png",
    backgroundImage: "assets/hamroDahachok/hamroDahachok_background.png",
    clientCode: 'LGW0MSQB9C',
    clientSecret: "181863",
    coOperativeName: 'hamroDahachok Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/hamroDahachok/hamroDahachok_logo.png',
    splashImage: "assets/hamroDahachok/hamroDahachok_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative globalMultiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/globalMulti/global_banner.png",
    backgroundImage: "assets/globalMulti/global_background.png",
    clientCode: 'HVAUGR1WUB',
    clientSecret: "173627",
    coOperativeName: 'globalMulti Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/globalMulti/global_logo.png',
    splashImage: "assets/globalMulti/global_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative dhanapraptiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/dhanaprapti/dhanaprapti_banner.png",
    backgroundImage: "assets/dhanaprapti/dhanaprapti_background.png",
    clientCode: 'B4R4X90Z4K',
    clientSecret: "209754",
    coOperativeName: 'dhanaprapti Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/dhanaprapti/dhanaprapti_logo.png',
    splashImage: "assets/dhanaprapti/dhanaprapti_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shubhashreeMultiCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shubhashreeMulti/shubhashreeMulti_banner.png",
    backgroundImage: "assets/shubhashreeMulti/shubhashreeMulti_background.png",
    clientCode: 'LKTKXRWIH4',
    clientSecret: "186278",
    coOperativeName: 'Shubhashree Multipurpose Co-operative Society Ltd.',
    coOperativeLogo: 'assets/shubhashreeMulti/shubhashreeMulti_logo.png',
    splashImage: "assets/shubhashreeMulti/shubhashreeMulti_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative belchautaraCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/belchautara/belchautara_banner.png",
    backgroundImage: "assets/belchautara/belchautara_background.png",
    clientCode: 'HRFPRIDAFG',
    clientSecret: "204591",
    coOperativeName: 'Belchautara Saving and Credit Cooperative Ltd',
    coOperativeLogo: 'assets/belchautara/belchautara_logo.png',
    splashImage: "assets/belchautara/belchautara_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeNawadeepCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeNawadeep/shreeNawadeep_banner.png",
    backgroundImage: "assets/shreeNawadeep/shreeNawadeep_background.png",
    clientCode: 'OK5465LF0V',
    clientSecret: "177524",
    coOperativeName: 'Shree Nawadeep Multipurpose Co-operative Ltd.',
    coOperativeLogo: 'assets/shreeNawadeep/shreeNawadeep_logo.png',
    splashImage: "assets/shreeNawadeep/shreeNawadeep_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shubhaShreeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shubhaShree/shubhaShree_banner.png",
    backgroundImage: "assets/shubhaShree/shubhaShree_background.png",
    clientCode: '57XRZEHTMC',
    clientSecret: "151881",
    coOperativeName: 'Shubha Shree Saving & Credit Co-operative Ltd',
    coOperativeLogo: 'assets/shubhaShree/shubhaShree_logo.png',
    splashImage: "assets/shubhaShree/shubhaShree_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative yugbaniCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/yugbani/yugbani_banner.png",
    backgroundImage: "assets/yugbani/yugbani_background.png",
    clientCode: 'D743MOWCBU',
    clientSecret: "157464",
    coOperativeName: 'Yugbani Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/yugbani/yugbani_logo.png',
    splashImage: "assets/yugbani/yugbani_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative bouddhamodeCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/bouddhamode/bouddhamode_banner.png",
    backgroundImage: "assets/bouddhamode/bouddhamode_background.png",
    clientCode: 'ABDDG2TLRP',
    clientSecret: "190516",
    coOperativeName: 'Shree Boudhamode Krishi Sahakari Sanstha	',
    coOperativeLogo: 'assets/bouddhamode/bouddhamode_logo.png',
    splashImage: "assets/bouddhamode/bouddhamode_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative mangalpurCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/mangalpur/mangalpur_banner.png",
    backgroundImage: "assets/mangalpur/mangalpur_background.png",
    clientCode: 'AM3WM748KK',
    clientSecret: "219935",
    coOperativeName: 'Shree Mangalpur Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/mangalpur/mangalpur_logo.png',
    splashImage: "assets/mangalpur/mangalpur_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative shreeGaneshCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/shreeGanesh/shreeGanesh_banner.png",
    backgroundImage: "assets/shreeGanesh/shreeGanesh_background.png",
    clientCode: 'XZLH1RFWZN',
    clientSecret: "195593",
    coOperativeName: 'Shree Ganesh Saving & Credit Co-operative Ltd.',
    coOperativeLogo: 'assets/shreeGanesh/shreeGanesh_logo.png',
    splashImage: "assets/shreeGanesh/shreeGanesh_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

//*****************// All sanakishan coop env //*****************//

  static final CoOperative skKohabara = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skKohabara/skKohabara_banner.png",
    backgroundImage: "assets/skKohabara/skKohabara_background.png",
    clientCode: '8HBJ3GXUN6',
    clientSecret: "132064",
    coOperativeName: 'Shree Boudhamode Krishi Sahakari Sanstha',
    coOperativeLogo: 'assets/skKohabara/skKohabara_logo.png',
    splashImage: "assets/skKohabara/skKohabara_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative skKhajurgachhi = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skKhajurgachhi/skKhajurgachhi_banner.png",
    backgroundImage: "assets/skKhajurgachhi/skKhajurgachhi_background.png",
    clientCode: 'NM2Q49HBNO',
    clientSecret: "140703",
    coOperativeName:
        'Sana Kisan Agriculture Cooperative Society Ltd. Khajurgachhi',
    coOperativeLogo: 'assets/skKhajurgachhi/skKhajurgachhi_logo.png',
    splashImage: "assets/skKhajurgachhi/skKhajurgachhi_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative skPatigaun = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skPatigaun/skPatigaun_banner.png",
    backgroundImage: "assets/skPatigaun/skPatigaun_background.png",
    clientCode: 'VX8Z9P1S9M',
    clientSecret: "151526",
    coOperativeName: 'Sana Kisan Agriculture Cooperative Society Ltd. Patigaun',
    coOperativeLogo: 'assets/skPatigaun/skPatigaun_logo.png',
    splashImage: "assets/skPatigaun/skPatigaun_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative skKhudunabari = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skKhudunabari/skKhudunabari_banner.png",
    backgroundImage: "assets/skKhudunabari/skKhudunabari_background.png",
    clientCode: '1ULEC7X5XE',
    clientSecret: "201567",
    coOperativeName:
        'Sana Kisan Agriculture Cooperative Society Ltd. khudunabari',
    coOperativeLogo: 'assets/skKhudunabari/skKhudunabari_logo.png',
    splashImage: "assets/skKhudunabari/skKhudunabari_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  static final CoOperative skJhurkiya = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skJhurkiya/skJhurkiya_banner.png",
    backgroundImage: "assets/skJhurkiya/skJhurkiya_background.png",
    clientCode: 'AJ55922FRN',
    clientSecret: "117059",
    coOperativeName: 'Sana Kisan Agriculture Cooperative Society Ltd. Jhurkiya',
    coOperativeLogo: 'assets/skJhurkiya/skJhurkiya_logo.png',
    splashImage: "assets/skJhurkiya/skJhurkiya_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );
  static final CoOperative skShankharpur = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/skShankharpur/skShankharpur_banner.png",
    backgroundImage: "assets/skShankharpur/skShankharpur_background.png",
    clientCode: '56ILOXKHY1',
    clientSecret: "214152",
    coOperativeName: 'Sana Kisan Agriculture Cooperative Ltd Shankharpur',
    coOperativeLogo: 'assets/skShankharpur/skShankharpur_logo.png',
    splashImage: "assets/skShankharpur/skShankharpur_splash.png",
    primaryColor: const Color(0xFF0b67bb),
  );

  //TODO need to add client id and secret

  static final CoOperative jharanaCoop = CoOperative(
    appStoreID: "",
    packageName: "",
    baseUrl: 'https://ismart.devanasoft.com.np/',
    bannerImage: "assets/jharana/jharana_banner.png",
    backgroundImage: "assets/jharana/jharana_background.png",
    clientCode: 'EHVNI7CZJ3', //using ismart code for production for now
    clientSecret: "126489",
    coOperativeName: 'Jharana Saving and Credit Cooperative Ltd.',
    coOperativeLogo: 'assets/jharana/jharana_logo.png',
    splashImage: "assets/jharana/jharana_splash.png",
    primaryColor: const Color.fromARGB(255, 57, 59, 61),
  );

//  DEV TEST700746
  static final CoOperative devLive = CoOperative(
    backgroundImage: "assets/images/ismart_background_image.jpg",
    bannerImage: "assets/images/ismart_banner.png",
    coOperativeName: '',
    coOperativeLogo: Assets.ismartLogo,
    clientCode: 'EHVNI7CZJ3',
    clientSecret: "126489",
    splashImage: "assets/images/ismart_splash.jpg",
    primaryColor: const Color(0xFF010C80),
    baseUrl: 'https://ismart.devanasoft.com.np/',
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
    shouldValidateCooperative: false,
  );

  static final CoOperative bhaktapurSaccos = CoOperative(
    backgroundImage: "assets/bhaktapur_saccos/bhaktapur_background.png",
    bannerImage: "assets/bhaktapur_saccos/bhaktapur_banner.png",
    coOperativeName: '',
    coOperativeLogo: "assets/bhaktapur_saccos/bhaktapur_logo.png",
    clientCode: 'EHVNI7CZJ3',
    clientSecret: "126489",
    splashImage: "assets/bhaktapur_saccos/bhaktapur_splash.png",
    primaryColor: const Color(0xFF010C80),
    baseUrl: 'https://ismart.devanasoft.com.np/',
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
    shouldValidateCooperative: false,
  );

  // // // // DEV TEST70074
  // static final CoOperative development = CoOperative(
  //   backgroundImage: "assets/images/ismart_background_image.jpg",

  //   bannerImage: "assets/images/ismart_banner.png",

  //   //  bannerImage: "assets/images/isamrt_banner.jpg",
  //   baseUrl: 'https://ismart.devanasoft.com.np/',
  //   clientCode: 'EHVNI7CZJ3',
  //   coOperativeName: '',
  //   coOperativeLogo: Assets.ismartLogo,
  //   clientSecret: "126489",
  //   splashImage: "assets/images/ismart_splash.jpg",

  //   primaryColor: const Color(0xFF010C80),
  // );

  // DEV TEST70074
  static final CoOperative development = CoOperative(
    baseUrl: 'http://103.198.9.222:1231/',
    bannerImage: "assets/images/ismart_banner.png",
    clientCode: 'PHZDAEF1CW',
    backgroundImage: "assets/images/ismart_background_image.jpg",
    coOperativeName: '',
    coOperativeLogo: Assets.ismartLogo,
    clientSecret: "156872",
    splashImage: "assets/images/ismart_splash.jpg",
    primaryColor: const Color(0xFF010C80),
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
  );
//  TEST for synergy cbs
  static final CoOperative synergyDevTest = CoOperative(
    baseUrl: 'http://103.198.9.222:1231/',
    bannerImage: "assets/images/ismart_banner.png",
    clientCode: '92D1PSNS6P',
    backgroundImage: "assets/images/ismart_background_image.jpg",
    coOperativeName: '',
    coOperativeLogo: Assets.ismartLogo,
    clientSecret: "131588",
    splashImage: "assets/images/ismart_splash.jpg",
    primaryColor: const Color(0xFF010C80),
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
  );
  //  TEST for finnact cbs
  static final CoOperative finnactDevTest = CoOperative(
    baseUrl: 'http://103.198.9.222:1231/',
    bannerImage: "assets/images/ismart_banner.png",
    clientCode: 'UDMIFJMEKF',
    backgroundImage: "assets/images/ismart_background_image.jpg",
    coOperativeName: '',
    coOperativeLogo: Assets.ismartLogo,
    clientSecret: "167956",
    splashImage: "assets/images/ismart_splash.jpg",
    primaryColor: const Color(0xFF010C80),
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
  );
  //  TEST for Systematic  cbs
  static final CoOperative systematicDevTest = CoOperative(
    baseUrl: 'http://103.198.9.222:1231/',
    bannerImage: "assets/images/ismart_banner.png",
    clientCode: 'O9YSV2CLCE',
    backgroundImage: "assets/images/ismart_background_image.jpg",
    coOperativeName: '',
    coOperativeLogo: Assets.ismartLogo,
    clientSecret: "129387",
    splashImage: "assets/images/ismart_splash.jpg",
    primaryColor: const Color(0xFF010C80),
    packageName: "com.devanasoft.ismart",
    appStoreID: "",
  );
}
