# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Run tests and build the release App Bundle"
  lane :build_and_test do
    # Navigate to the project root to run flutter commands
    Dir.chdir("..") do
      sh("flutter", "pub", "get")
      sh("flutter", "analyze")
      # sh("flutter", "test")
      sh("flutter", "build", "appbundle", "--release","flavour","kamdhenu","-t","lib/main.dart")
    end
  end

  desc "Deploy to Google Play Internal track"
  lane :deploy do
    build_and_test # Run the build lane first

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      # For deployment, you must set up Google Play credentials
      # json_key: "path/to/your/play-store-credentials.json"
    )
  end
end