name: Deploy to Play Store

on:
  push:
    branches:
      - feat/subash/proj_upgrade

env:
  FLUTTER_VERSION: "3.27.0"
  GRADLE_VERSION: "8.9"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup java 17 (for Gradle 8.x)
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run Flutter doctor
        run: flutter doctor -v

      - name: Get Flutter dependencies
        run: flutter pub get

      #   - name: Verify Flutter format
      #     run: flutter format --set-exit-if-changed .

      #   - name: Analyze Flutter code
      #     run: flutter analyze

      - name: Build APK
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          flutter build apk --release

      - name: Build App Bundle
        run: |
          export JAVA_HOME=$JAVA_HOME_17_X64
          flutter build appbundle --release

    #   - name: Upload Artifacts
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: release-artifacts
    #       path: |
    #         build/app/outputs/flutter-apk/app-release.apk
    #         build/app/outputs/bundle/release/app-release.aab
    #       retention-days: 5

    #   - name: Upload to Play Store
    #     uses: r0adkll/upload-google-play@v1
    #     with:
    #       serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
    #       packageName: com.your.package.name # Replace with your package name
    #       releaseFiles: build/app/outputs/bundle/release/app-release.aab
    #       track: production # or beta/alpha/rollout
    #       # status: completed # Uncomment for immediate rollout
    #       # userFraction: 0.5 # Uncomment for percentage rollout
